### ISSUE TITLE
Ambiguous Overload when compiling for Device OS 2.0.0-rc.1

### ISSUE THREAD

**Issue by TrikkStar** [rickkas7/JsonParserGeneratorRK#8]
Getting the following error when trying to compile my code on the latest OS release candidate:
`app_path/lib/JsonParserGeneratorRK/src/JsonParserGeneratorRK.h:1067:3: error: call of overloaded 'insertValue(long long int&)' is ambiguous`
Code compiles fine on 1.5.2.

**Comment by rickkas7** [comment]
`long long int` (64-bit signed) is not a valid type to pass to insertValue. If you really need 64-bit support you'll need to manually convert it. If the value isn't really that long, you'll need to cast to 32-bit value like long instead.
